"""AlphaZero-style iteration loop: self-play, replay-buffer training, repeat.

Each iteration:
  1. The current network plays ``games_per_iteration`` self-play games. Every
     position visited becomes a training sample whose policy target is the MCTS
     visit distribution and whose value target is the eventual game outcome.
  2. The new samples are added to a fixed-size replay buffer (oldest chunks
     evicted once it overflows).
  3. The network is trained for ``training_steps_per_iteration`` mini-batch
     steps on uniformly-sampled positions from the buffer.
  4. A checkpoint is saved and the next iteration begins with the updated net.

What this script does *not* do (intentionally, to keep it tractable):
  - Run self-play across multiple processes. One game at a time.
  - Gate new checkpoints against the previous one via match play. AlphaGo Zero
    did this; AlphaZero dropped it. We drop it too — the latest checkpoint is
    always used for the next round of self-play.

Numerical detail to keep in mind: the policy loss is the cross-entropy of the
MCTS visit distribution against the model's softmax over *legal* moves only.
Illegal moves are masked out of the softmax denominator before computing
log-probabilities, matching how the network is used at inference.
"""

from __future__ import annotations

import argparse
import json
import os
import time
from dataclasses import dataclass, asdict, field
from datetime import datetime

import numpy as np
import torch

from neural_network import (
    BOARD_ENCODING_VERSION,
    ChessModel,
    DEVICE,
    MODEL_PATH,
    MOVE_VOCAB_SIZE,
    RESIDUAL_BLOCKS,
    RESIDUAL_FILTERS,
    mask_illegal_logits,
)
from load_model import load_trained_model
from self_play import SelfPlayConfig, generate_self_play_games


@dataclass
class TrainingConfig:
    """Hyperparameters for the self-play training loop."""
    num_iterations: int = 20
    games_per_iteration: int = 50
    replay_buffer_capacity: int = 200_000     # positions
    training_steps_per_iteration: int = 1000
    batch_size: int = 256
    learning_rate: float = 1e-3
    weight_decay: float = 1e-4
    value_loss_weight: float = 1.0
    grad_clip: float = 1.0
    # File system
    chunks_dir: str = 'data/selfplay_chunks'
    checkpoint_dir: str = 'model/selfplay_checkpoints'
    log_path: str = 'data/selfplay_log.jsonl'
    # Bootstrap from an existing supervised checkpoint?
    init_checkpoint: str | None = None
    # Re-use chunks generated by previous runs that already live in chunks_dir.
    seed_buffer_from_dir: bool = True


class ReplayBuffer:
    """Chronologically-ordered chunks of self-play positions, FIFO eviction.

    Positions are stored as parallel arrays inside chunks; sampling picks a
    global flat index uniformly across all positions currently in the buffer
    and translates it to (chunk_idx, within_chunk_idx).
    """

    def __init__(self, capacity: int):
        self.capacity = capacity
        self.chunks: list[dict] = []

    def total_positions(self) -> int:
        return sum(c['boards'].shape[0] for c in self.chunks)

    def add_chunk_from_path(self, path: str) -> int:
        data = np.load(path)
        chunk = {
            'boards': data['boards'],
            'move_seqs': data['move_seqs'],
            'legal_move_indices': data['legal_move_indices'],
            'legal_move_offsets': data['legal_move_offsets'],
            'visit_counts': data['visit_counts'],
            'value_target': data['value_target'],
            'path': path,
        }
        n = chunk['boards'].shape[0]
        if n == 0:
            return 0
        self.chunks.append(chunk)
        self._evict_to_capacity()
        return n

    def _evict_to_capacity(self) -> None:
        while self.total_positions() > self.capacity and len(self.chunks) > 1:
            self.chunks.pop(0)

    def sample_batch(self, batch_size: int) -> dict | None:
        if not self.chunks:
            return None
        sizes = np.array(
            [c['boards'].shape[0] for c in self.chunks], dtype=np.int64
        )
        total = int(sizes.sum())
        if total == 0:
            return None

        flat = np.random.randint(0, total, size=batch_size)
        cumsum = np.cumsum(sizes)
        chunk_idx = np.searchsorted(cumsum, flat, side='right')
        starts = np.concatenate([[0], cumsum[:-1]])
        within = flat - starts[chunk_idx]

        boards = np.empty((batch_size, 8, 8, 17), dtype=np.float32)
        move_seqs = np.empty((batch_size, 10, 132), dtype=np.float32)
        value_target = np.empty(batch_size, dtype=np.float32)
        # Legal moves vary in count per position; build a dense (B, V) policy
        # target and legal mask here so the training step is simple.
        policy_target = np.zeros((batch_size, MOVE_VOCAB_SIZE), dtype=np.float32)
        legal_mask = np.zeros((batch_size, MOVE_VOCAB_SIZE), dtype=bool)

        for row, (ci, wi) in enumerate(zip(chunk_idx, within)):
            chunk = self.chunks[ci]
            boards[row] = chunk['boards'][wi]
            move_seqs[row] = chunk['move_seqs'][wi]
            value_target[row] = chunk['value_target'][wi]

            offsets = chunk['legal_move_offsets']
            start, end = int(offsets[wi]), int(offsets[wi + 1])
            legal_idx = chunk['legal_move_indices'][start:end]
            visits = chunk['visit_counts'][start:end].astype(np.float32)
            legal_mask[row, legal_idx] = True
            total_visits = visits.sum()
            if total_visits > 0:
                policy_target[row, legal_idx] = visits / total_visits

        return {
            'boards': boards,
            'move_seqs': move_seqs,
            'legal_mask': legal_mask,
            'policy_target': policy_target,
            'value_target': value_target,
        }


def distribution_train_step(
    model: ChessModel,
    optimizer: torch.optim.Optimizer,
    batch: dict,
    value_loss_weight: float,
    grad_clip: float | None,
    device: torch.device,
) -> dict:
    """One gradient step with MCTS visit-distribution policy targets.

    Policy loss: -sum_a target(a) * log_softmax_legal(logits)(a)
    Value loss:  MSE between value head output and {-1, 0, +1} game outcome.
    """
    model.train()

    boards = torch.from_numpy(batch['boards']).float().permute(0, 3, 1, 2).to(device)
    move_seqs = torch.from_numpy(batch['move_seqs']).float().to(device)
    legal_mask = torch.from_numpy(batch['legal_mask']).to(device)
    policy_target = torch.from_numpy(batch['policy_target']).float().to(device)
    value_target = torch.from_numpy(batch['value_target']).float().to(device)

    optimizer.zero_grad()

    policy_logits, value_pred = model(boards, move_seqs)
    masked_logits = mask_illegal_logits(policy_logits, legal_mask)
    log_probs = torch.log_softmax(masked_logits.float(), dim=1)
    # Only positions where target > 0 contribute; that subset is the set of
    # legal moves with non-zero MCTS visit counts.
    policy_loss = -(policy_target * log_probs).sum(dim=1).mean()
    value_loss = ((value_pred.float() - value_target) ** 2).mean()
    total = policy_loss + value_loss_weight * value_loss

    total.backward()
    if grad_clip is not None and grad_clip > 0:
        torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
    optimizer.step()

    with torch.no_grad():
        # Top-1 agreement: argmax of model legal-softmax vs argmax of MCTS visits.
        model_top = masked_logits.argmax(dim=1)
        target_top = policy_target.argmax(dim=1)
        # Only count rows where some target was non-zero (i.e. there were visits).
        has_target = (policy_target.sum(dim=1) > 0)
        if has_target.any():
            top1 = float(
                (model_top[has_target] == target_top[has_target]).float().mean().item()
            )
        else:
            top1 = float('nan')

    return {
        'loss': float(total.item()),
        'policy_loss': float(policy_loss.item()),
        'value_loss': float(value_loss.item()),
        'top1_agreement': top1,
    }


def _save_checkpoint(model: ChessModel, optimizer: torch.optim.Optimizer,
                     path: str, iteration: int, extra: dict) -> None:
    os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
    payload = {
        'iteration': iteration,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'board_encoding': BOARD_ENCODING_VERSION,
        'residual_filters': RESIDUAL_FILTERS,
        'residual_blocks': RESIDUAL_BLOCKS,
        # The supervised loader checks for these and refuses to load mismatches.
        'value_loss_weight': extra.get('value_loss_weight'),
        'training_kind': 'self_play_alphazero',
    }
    payload.update({k: v for k, v in extra.items() if k != 'value_loss_weight'})
    torch.save(payload, path)


def _append_log(log_path: str, record: dict) -> None:
    os.makedirs(os.path.dirname(log_path) or '.', exist_ok=True)
    with open(log_path, 'a', encoding='utf-8') as f:
        f.write(json.dumps(record) + '\n')


def run_iteration(
    iteration: int,
    model: ChessModel,
    optimizer: torch.optim.Optimizer,
    buffer: ReplayBuffer,
    self_play_config: SelfPlayConfig,
    training_config: TrainingConfig,
    seed: int | None,
) -> dict:
    """One self-play + training iteration. Returns a summary record."""
    iter_start = time.monotonic()

    # 1. Self-play
    sp_summary = generate_self_play_games(
        model,
        num_games=training_config.games_per_iteration,
        config=self_play_config,
        output_dir=training_config.chunks_dir,
        chunk_prefix=f'iter{iteration:04d}',
        seed=seed,
        verbose=True,
    )

    # 2. Add to buffer
    added = buffer.add_chunk_from_path(sp_summary['chunk_path'])
    buffer_size = buffer.total_positions()

    # 3. Train
    train_metrics: list[dict] = []
    train_start = time.monotonic()
    if buffer_size > 0:
        for step in range(training_config.training_steps_per_iteration):
            batch = buffer.sample_batch(training_config.batch_size)
            if batch is None:
                break
            metrics = distribution_train_step(
                model, optimizer, batch,
                value_loss_weight=training_config.value_loss_weight,
                grad_clip=training_config.grad_clip,
                device=DEVICE,
            )
            train_metrics.append(metrics)
            if (step + 1) % max(training_config.training_steps_per_iteration // 5, 1) == 0:
                avg_recent = _mean_metrics(train_metrics[-50:])
                print(
                    f"    step {step + 1}/{training_config.training_steps_per_iteration} | "
                    f"loss={avg_recent['loss']:.4f} "
                    f"pol={avg_recent['policy_loss']:.4f} "
                    f"val={avg_recent['value_loss']:.4f} "
                    f"top1={avg_recent['top1_agreement']:.3f}"
                )
    train_elapsed = time.monotonic() - train_start

    # 4. Checkpoint
    ckpt_path = os.path.join(
        training_config.checkpoint_dir,
        f'selfplay_iter{iteration:04d}.pt',
    )
    train_summary = _mean_metrics(train_metrics) if train_metrics else {}
    _save_checkpoint(
        model, optimizer, ckpt_path, iteration,
        extra={
            'value_loss_weight': training_config.value_loss_weight,
            'iteration_self_play_games': training_config.games_per_iteration,
            'iteration_training_steps': len(train_metrics),
            'buffer_positions_after': buffer_size,
            'mean_train_loss': train_summary.get('loss'),
            'mean_policy_loss': train_summary.get('policy_loss'),
            'mean_value_loss': train_summary.get('value_loss'),
            'mean_top1_agreement': train_summary.get('top1_agreement'),
        },
    )

    iter_elapsed = time.monotonic() - iter_start
    summary = {
        'iteration': iteration,
        'timestamp': datetime.now().isoformat(timespec='seconds'),
        'self_play': sp_summary,
        'chunk_added_positions': added,
        'buffer_positions': buffer_size,
        'training_steps': len(train_metrics),
        'training_elapsed_seconds': train_elapsed,
        'iteration_elapsed_seconds': iter_elapsed,
        'mean_train_metrics': train_summary,
        'checkpoint_path': ckpt_path,
    }
    _append_log(training_config.log_path, summary)
    print(
        f"  iter {iteration}: self_play={sp_summary['elapsed_seconds']:.1f}s "
        f"train={train_elapsed:.1f}s total={iter_elapsed:.1f}s "
        f"buffer={buffer_size} ckpt={ckpt_path}"
    )
    return summary


def _mean_metrics(metrics: list[dict]) -> dict:
    if not metrics:
        return {}
    out: dict[str, float] = {}
    keys = metrics[0].keys()
    for k in keys:
        vals = [m[k] for m in metrics if not (isinstance(m[k], float) and np.isnan(m[k]))]
        out[k] = float(np.mean(vals)) if vals else float('nan')
    return out


def _seed_buffer_from_dir(buffer: ReplayBuffer, chunks_dir: str) -> int:
    """Load all existing chunks in chronological order so a restart resumes."""
    if not os.path.isdir(chunks_dir):
        return 0
    files = sorted(
        os.path.join(chunks_dir, f)
        for f in os.listdir(chunks_dir)
        if f.endswith('.npz')
    )
    total = 0
    for f in files:
        try:
            total += buffer.add_chunk_from_path(f)
        except Exception as exc:
            print(f"  warning: could not load {f}: {exc}")
    return total


def run_loop(
    training_config: TrainingConfig,
    self_play_config: SelfPlayConfig,
    start_iteration: int = 1,
    seed: int | None = None,
) -> None:
    # Resume safety: when continuing from a later iteration without an explicit
    # init checkpoint, load the *previous* iteration's self-play checkpoint
    # rather than silently falling back to the supervised model (which would
    # throw away all self-play progress and overwrite the iteration files).
    resume_ckpt = None
    if start_iteration > 1 and not training_config.init_checkpoint:
        resume_ckpt = os.path.join(
            training_config.checkpoint_dir,
            f'selfplay_iter{start_iteration - 1:04d}.pt',
        )
        if not os.path.exists(resume_ckpt):
            raise FileNotFoundError(
                f"--start_iteration {start_iteration} implies resuming, but the "
                f"previous checkpoint {resume_ckpt!r} was not found. Pass "
                "--init_checkpoint explicitly, or start from iteration 1."
            )

    if resume_ckpt is not None:
        print(f"Resuming from self-play checkpoint {resume_ckpt}")
        model = load_trained_model(resume_ckpt)
    elif training_config.init_checkpoint:
        model = load_trained_model(training_config.init_checkpoint)
    elif os.path.exists(MODEL_PATH):
        print(f"Bootstrapping from supervised checkpoint at {MODEL_PATH}")
        model = load_trained_model(MODEL_PATH)
    else:
        print("No checkpoint found — starting from a freshly-initialized model.")
        model = ChessModel().to(DEVICE)
        model.value_head_trained = True

    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=training_config.learning_rate,
        weight_decay=training_config.weight_decay,
    )

    buffer = ReplayBuffer(capacity=training_config.replay_buffer_capacity)
    if training_config.seed_buffer_from_dir:
        seeded = _seed_buffer_from_dir(buffer, training_config.chunks_dir)
        if seeded:
            print(f"Seeded buffer with {seeded} positions from {training_config.chunks_dir}")

    for iteration in range(start_iteration, start_iteration + training_config.num_iterations):
        print(f"\n=== Iteration {iteration} ===")
        run_iteration(
            iteration, model, optimizer, buffer,
            self_play_config, training_config,
            seed=(None if seed is None else seed + iteration),
        )


def _build_configs(args) -> tuple[TrainingConfig, SelfPlayConfig]:
    training_config = TrainingConfig(
        num_iterations=args.iterations,
        games_per_iteration=args.games_per_iteration,
        replay_buffer_capacity=args.replay_buffer_capacity,
        training_steps_per_iteration=args.training_steps,
        batch_size=args.batch_size,
        learning_rate=args.learning_rate,
        weight_decay=args.weight_decay,
        value_loss_weight=args.value_loss_weight,
        grad_clip=args.grad_clip,
        chunks_dir=args.chunks_dir,
        checkpoint_dir=args.checkpoint_dir,
        log_path=args.log_path,
        init_checkpoint=args.init_checkpoint,
        seed_buffer_from_dir=not args.fresh_buffer,
    )
    self_play_config = SelfPlayConfig(
        mcts_simulations=args.mcts_simulations,
        c_puct=args.c_puct,
        mcts_batch_size=args.mcts_batch_size,
        policy_temperature=args.policy_temperature,
        temperature_threshold=args.temperature_threshold,
        temperature_high=args.temperature_high,
        temperature_low=args.temperature_low,
        add_root_noise=not args.no_root_noise,
        dirichlet_alpha=args.dirichlet_alpha,
        dirichlet_epsilon=args.dirichlet_epsilon,
        max_plies=args.max_plies,
    )
    return training_config, self_play_config


def main():
    parser = argparse.ArgumentParser(
        description='AlphaZero-style self-play training loop.'
    )
    # Loop
    parser.add_argument('--iterations', type=int, default=20)
    parser.add_argument('--games_per_iteration', type=int, default=50)
    parser.add_argument('--training_steps', type=int, default=1000)
    parser.add_argument('--start_iteration', type=int, default=1)
    parser.add_argument('--seed', type=int, default=None)
    # Training
    parser.add_argument('--batch_size', type=int, default=256)
    parser.add_argument('--learning_rate', type=float, default=1e-3)
    parser.add_argument('--weight_decay', type=float, default=1e-4)
    parser.add_argument('--value_loss_weight', type=float, default=1.0)
    parser.add_argument('--grad_clip', type=float, default=1.0)
    parser.add_argument('--replay_buffer_capacity', type=int, default=200_000)
    parser.add_argument('--fresh_buffer', action='store_true',
                        help='Ignore existing chunks in --chunks_dir on startup.')
    # File system
    parser.add_argument('--chunks_dir', default='data/selfplay_chunks')
    parser.add_argument('--checkpoint_dir', default='model/selfplay_checkpoints')
    parser.add_argument('--log_path', default='data/selfplay_log.jsonl')
    parser.add_argument('--init_checkpoint', default=None,
                        help='Bootstrap from this checkpoint path. Defaults to '
                             'the supervised MODEL_PATH if it exists.')
    # MCTS / self-play
    parser.add_argument('--mcts_simulations', type=int, default=400)
    parser.add_argument('--c_puct', type=float, default=1.5)
    parser.add_argument('--mcts_batch_size', type=int, default=16)
    parser.add_argument('--policy_temperature', type=float, default=1.0)
    parser.add_argument('--temperature_threshold', type=int, default=30)
    parser.add_argument('--temperature_high', type=float, default=1.0)
    parser.add_argument('--temperature_low', type=float, default=0.0)
    parser.add_argument('--no_root_noise', action='store_true')
    parser.add_argument('--dirichlet_alpha', type=float, default=0.3)
    parser.add_argument('--dirichlet_epsilon', type=float, default=0.25)
    parser.add_argument('--max_plies', type=int, default=256)

    args = parser.parse_args()
    training_config, self_play_config = _build_configs(args)
    run_loop(
        training_config,
        self_play_config,
        start_iteration=args.start_iteration,
        seed=args.seed,
    )


if __name__ == '__main__':
    main()
